export class securitybond{
   ID :number;
   SecurityDescription:string;
 SecurityName :string;
AssetType :string;
 InvestmentType:string;
 TradingFactor :number;
 PricingFactor :number;
ISIN:string;
 BBGTicker :string;
  BBGUniqueID :string;
   SEDOL:string;
   FirstCouponDate:string;
Cap:string;
 FloorValue:string;
  CouponFrequency :number;
    Coupon :number;
    CouponType :string;
   Spread :string;
     CallableFlag :string;
  FixtoFloatFlag:string;
  PutableFlag :string;
 IssueDate:string;
 LastResetDate :string;
   Maturity:string;
 CallNotificationMaxDays:number;
PutNotificationMaxDays:number;
  PenultimateCouponDate :string;
  ResetFrequency :string;
   HasPosition :string;
MacaulayDuration :number;
   Volatility_30D :number;
    Volatility_90D :number;
    Convexity :number;
     AverageVolume_30Day:number; 
     PFAssetClass :string;
    PFCountry :string;
     PFCreditRating :string;
   PFCurrency :string;
    PFInstrument :string;
     PFLiquidityProfile :string;
     PFMaturity:string;
    PFNAICSCode:string;
    PFRegion:string;
     PFSector :string;
     PFSubAssetClass :string;
   BloombergIndustryGroup :string;
    BloombergIndustrySubGroup:string;
   BloombergIndustrySector:string;
    CountryofIssuance :string;
IssueCurrency :string;
   IssuerName:string;
    RiskCurrency :string;
   PutDate :string;
  PutPrice :number; 
    AskPrice :number; 
     HighPrice :number; 
     LowPrice :number; 
  OpenPrice :number; 
   Volume :number; 
   BidPrice :number; 
    LastPrice :number; 
    CallDate :string;
    CallPrice :number; 
}